# Generated by Django 5.1.3 on 2025-05-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_question_scoring_points'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='factors',
            field=models.ManyToManyField(blank=True, related_name='trainings', to='surveys.factor'),
        ),
    ]
