# Generated by Django 5.1.3 on 2025-05-22 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnoveranalytics',
            options={},
        ),
        migrations.AddField(
            model_name='employeeturnover',
            name='factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnover_records', to='surveys.factor'),
        ),
    ]
