# Generated by Django 5.1.3 on 2025-05-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_turnoveranalytics_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeturnover',
            name='performance_rating',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeturnover',
            name='tenure_months',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
