# Generated by Django 5.2.1 on 2025-05-21 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='weight',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddField(
            model_name='question',
            name='has_scoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='scoring_guide',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyassignment',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
