# Generated by Django 5.2.1 on 2025-05-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_factor_weight_question_has_scoring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scoring_points',
            field=models.FloatField(default=0.0),
        ),
    ]
